if (!require(shiny)){install.packages("shiny")}; library(shiny)
suppressPackageStartupMessages({   
  # load libraries including tesseract for OCR
  if (!(require(tesseract))) {install.packages("tesseract")};  library(tesseract)
  if (!(require(Hmisc))) {install.packages("Hmisc")};  library(Hmisc)
  if (!(require(xml2))) {install.packages("xml2")};  library(xml2)
  if (!(require(stringr))) {install.packages("stringr")};  library(stringr)
  if (!(require(tibble))) {install.packages("tibble")};  library(tibble)
  if (!(require(pdftools))) {install.packages("pdftools")};  library(pdftools)
  if (!(require(quanteda))) {install.packages("quanteda")};  library(quanteda)
  if (!(require(DT))) {install.packages("DT")};  library(DT)  
  if (!(require(wordcloud))) {install.packages("wordcloud")};  library(wordcloud)  
  if (!(require(tm))) {install.packages("tm")};  library(tm)  
  if (!(require(jpeg))) {install.packages("jpeg")};  library(jpeg)  
})
